name: host
on:
  pull_request:
    paths:
      - 'packages/host/**.ts'
      - 'packages/host/**.json'
      - '.github/workflows/host.yml'
  push:
    branches:
      - main
    paths:
      - 'packages/host/**.ts'
      - 'packages/host/**.json'
      - '.github/workflows/host.yml'
jobs:
  host:
    name: host
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: ['lts/Iron', 'latest']
    steps:
      - uses: actions/checkout@v2
      - name: Set up Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
      - name: Set up Terraform
        uses: ./.github/actions/setup-terraform
      - name: Install
        run: npm install
      - name: Build
        run: npm run build -w packages/host
      - name: Test
        run: vitest --run
      - name: Lint
        run: cd ./packages/host && npm run lint
