name: mock
on:
  pull_request:
    paths:
      - 'packages/mock/**.ts'
      - 'packages/mock/**.json'
      - '.github/workflows/mock.yml'
  push:
    branches:
      - main
    paths:
      - 'packages/mock/**.ts'
      - 'packages/mock/**.json'
      - '.github/workflows/mock.yml'
jobs:
  mock:
    name: mock
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: ['lts/Iron', 'latest']
    steps:
      - uses: actions/checkout@v2
      - name: Set up Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
      - name: Set up Terraform
        uses: ./.github/actions/setup-terraform
      - name: Install
        run: npm install
      - name: Build
        run: |
          npm run build -w packages/mock
      - name: Test
        run: npm test -w packages/mock
      - name: Lint
        run: cd ./packages/mock && npm run lint
