name: output
on:
  pull_request:
    paths:
      - 'packages/output/**.ts'
      - 'packages/output/**.json'
      - '.github/workflows/output.yml'
  push:
    branches:
      - main
    paths:
      - 'packages/output/**.ts'
      - 'packages/output/**.json'
      - '.github/workflows/output.yml'
jobs:
  output:
    name: output
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: ['lts/Iron', 'latest']
    steps:
      - uses: actions/checkout@v2
      - name: Set up Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
      - name: Set up Terraform
        uses: ./.github/actions/setup-terraform
      - name: Install
        run: npm install
      - name: Build
        run: npm run build -w packages/output
      - name: Lint
        run: cd ./packages/output && npm run lint
