name: readline
on:
  pull_request:
    paths:
      - 'packages/readline/**.ts'
      - 'packages/readline/**.json'
      - '.github/workflows/readline.yml'
  push:
    branches:
      - main
    paths:
      - 'packages/readline/**.ts'
      - 'packages/readline/**.json'
      - '.github/workflows/readline.yml'
jobs:
  readline:
    name: readline
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: ['lts/Iron', 'latest']
    steps:
      - uses: actions/checkout@v2
      - name: Set up Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
      - name: Set up Terraform
        uses: ./.github/actions/setup-terraform
      - name: Install
        run: npm install
      - name: Build
        run: npm run build -w packages/readline
      - name: Test
        run: vitest --run
      - name: Lint
        run: cd ./packages/readline && npm run lint
