name: telemetry
on:
  pull_request:
    paths:
      - 'packages/telementry/**.ts'
      - 'packages/telemetry/grabthar.yml'
      - 'packages/entrypoint/**.json'
  push:
    branches:
      - main
    paths:
      - 'packages/telementry/**.ts'
      - 'packages/telemetry/grabthar.yml'
      - 'packages/entrypoint/**.json'
jobs:
  telemetry:
    name: telemetry
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: ['lts/Iron', 'latest']
    steps:
      - uses: actions/checkout@v2
      - name: Set up Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
      - name: Set up Terraform
        uses: ./.github/actions/setup-terraform
      - name: Install
        run: npm install
      - name: Lint
        run: npm run lint -w packages/telemetry
