name: vitest
on:
  pull_request:
    paths:
      - 'packages/vitest/**.ts'
      - 'packages/vitest/**.json'
      - '.github/workflows/vitest.yml'
  push:
    branches:
      - main
    paths:
      - 'packages/vitest/**.ts'
      - 'packages/vitest/**.json'
      - '.github/workflows/vitest.yml'
jobs:
  vitest:
    name: vitest
    runs-on: ubuntu-lavitest
    strategy:
      matrix:
        node-version: ['lts/Iron', 'latest']
    steps:
      - uses: actions/checkout@v2
      - name: Set up Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
      - name: Set up Terraform
        uses: ./.github/actions/setup-terraform
      - name: Install
        run: npm install
      - name: Build
        run: npm run build -w packages/vitest
      - name: Test
        run: npm test -w packages/vitest
      - name: Lint
        run: cd ./packages/vitest && npm run lint
